version: '3'
services:
  # 服务名称
  ApiTestManage:
    # 镜像:版本
    container_name: ApiTestManage
    image: apitest:v1
    # 数据卷 映射本地文件到容器
    volumes:
      - /home/ApiTestManage:/Project/apitest/ApiTestManage
      - /usr/share/zoneinfo/Asia/:/usr/share/zoneinfo/Asia/
    ports:
      - "8091:8091"

    environment:
      FLASK_CONFIG: Production
      TZ: Asia/Shanghai
    command: gunicorn -c ./ApiTestManage/gunicorn_config.py manage:app --chdir /Project/apitest/ApiTestManage

